# if dont want to mess with your os env
version: '3.1'
services:
  simpleweb:
    build: ./
    restart: always
    depends_on:
      - db
    environment:
      db_name: todo
      db_username: root
      db_password: IIIdevops123!
      db_host: db
    ports:
      - 8080
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: IIIdevops123!
    volumes:
      - ./db:/docker-entrypoint-initdb.d:rw
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080
